### ISSUE TITLE
”HelloWorld"と応えるトリガーを変更する

### ISSUE THREAD

**Issue by i-ishikawa-106** [findix-slackapp/slackapp-hello-world3#1]
### 要件
- 現在："Hi"と呼びかけられたら”HelloWorld"と応える。
- 今後：なにか呼びかけられたら”HelloWorld"と応える。

**Comment by i-ishikawa-106** [comment]
@t-kikkawa issue作ってみました。
Label、Projects、Milestoneって設定必要？（Wikiに設定しろとある。。）

**Comment by t-kikkawa** [comment]
@i-ishikawa-106 対応しました。
Labelは任意でよいと思います。
Projectは「findix-slackapp」にのみ作るので、リポジトリ毎に必要なければ無くてもよいです。
Milestoneも取り敢えず「バージョンXXX」という風にリリース必要がなければ無くてもよいです。
いずれも「slackapp-hello-world」ではいろいろいじって試してみたので設定したが、必要なければ無くてもよい。

**Comment by i-ishikawa-106** [comment]
@t-kikkawa Wikiを変更しました。 https://github.com/findix-slackapp/docs/wiki/%E6%94%B9%E4%BF%AE%E6%89%8B%E9%A0%86
