### ISSUE TITLE
指示に従いボットが発言する

### ISSUE THREAD

**Issue by i-ishikawa-106** [findix-slackapp/slackapp-hello-world3#24]
以下を指示すると指示どおりにボットが発言する。
- 発言する内容
- 発言するチャンネル

UIは、スラッシュコマンド（/remind みたいな）のような感じ？
指示できる人を、プロジェクトメンバーに絞りたい。

**Comment by t-kikkawa** [comment]
@i-ishikawa-106 
プロジェクトメンバーに絞るとは「prj-slackapp」に参加しているメンバーということで宜しいでしょうか？

**Comment by i-ishikawa-106** [comment]
@t-kikkawa 

> プロジェクトメンバーに絞るとは「prj-slackapp」に参加しているメンバーということで宜しいでしょうか？

「prj-slackapp」とは、slackのチャンネルを指していますね？で、APIかなんかでそのチャンネルのメンバーを取得すると。
いったんそれで構いません。が、公開チャンネルで誰でも参加できるので、プライベートなチャンネルを作ってそこからメンバーを取得するほうが良いかも。

**Comment by t-kikkawa** [comment]
@i-ishikawa-106 
とりあえずは発言内容にメンション出来なくても良いですか？

**Comment by i-ishikawa-106** [comment]
okです！

2019年6月19日(水) 13:58 findix-kikkawa <notifications@github.com>:

**Comment by t-kikkawa** [comment]
/hello_worldコマンドを作りました。
発言させるチャンネルと発言内容をカンマ区切りで渡します。
　例 /hell_world prj-slackapp-test,hoge
但し、発言内容にメンションは入れられない。
